using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using PrismZone.Core;

namespace PrismZone.EditorTools
{
    /// <summary>
    /// Writes <c>Assets/Scripts/Core/FlagKeys.cs</c> auto-side (FRAMEWORK.md §6.2).
    ///
    /// For each TSV row:
    ///   - <c>category=dialogue</c> with id like "T-01" → const "T_01" =
    ///     "dialogue.T-01.triggered"
    ///   - <c>category=item</c> with id starting "item." → const "Has_Xxx" =
    ///     "inventory.has.{base id}"
    ///
    /// FlagKeysBuiltin.cs (hand-written) and FlagKeys.cs (auto) are partials of the
    /// same static class, so callers reference both via `FlagKeys.Dialogue.T_01` etc.
    /// </summary>
    public static class FlagKeysGenerator
    {
        private const string OutputPath = "Assets/Scripts/Core/FlagKeys.cs";

        public static int Regenerate(IEnumerable<TextEntry> entries)
        {
            var dialogueIds = new SortedSet<string>(System.StringComparer.Ordinal);
            var itemBaseIds = new SortedSet<string>(System.StringComparer.Ordinal);

            foreach (var e in entries)
            {
                if (e == null || string.IsNullOrEmpty(e.id)) continue;
                if (e.category == TextEntry.Category.dialogue)
                {
                    dialogueIds.Add(e.id);
                }
                else if (e.category == TextEntry.Category.item && e.id.StartsWith("item."))
                {
                    // Strip "item." prefix AND trailing ".name"/".desc" — keep middle
                    // segments so item.key.storage.name → "key.storage" (const Key_Storage)
                    // and item.key.stairs_4f.name → "key.stairs_4f" (const Key_Stairs_4F).
                    string baseId = e.id.Substring("item.".Length);
                    if (baseId.EndsWith(".name"))      baseId = baseId.Substring(0, baseId.Length - ".name".Length);
                    else if (baseId.EndsWith(".desc")) baseId = baseId.Substring(0, baseId.Length - ".desc".Length);
                    if (!string.IsNullOrEmpty(baseId)) itemBaseIds.Add(baseId);
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine("// AUTO-GENERATED by Editor/FlagKeysGenerator. DO NOT EDIT BY HAND.");
            sb.AppendLine("// Hand-written entries live in FlagKeysBuiltin.cs.");
            sb.AppendLine("// Re-run via: Tools > Prism Zone > Import Text Table");
            sb.AppendLine();
            sb.AppendLine("namespace PrismZone.Core");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class FlagKeys");
            sb.AppendLine("    {");

            // Dialogue
            sb.AppendLine("        public static class Dialogue");
            sb.AppendLine("        {");
            foreach (var id in dialogueIds)
            {
                string constName = MakeConstName(id);
                sb.AppendLine($"            public const string {constName} = \"dialogue.{id}.triggered\";");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // Inventory
            sb.AppendLine("        public static class Inventory");
            sb.AppendLine("        {");
            foreach (var baseId in itemBaseIds)
            {
                string constName = "Has_" + MakeConstName(baseId);
                sb.AppendLine($"            public const string {constName} = \"inventory.has.{baseId}\";");
            }
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            // Skip writing if output is byte-identical — avoid unnecessary recompiles.
            string newContent = sb.ToString();
            if (File.Exists(OutputPath))
            {
                string oldContent = File.ReadAllText(OutputPath);
                if (oldContent == newContent) return dialogueIds.Count + itemBaseIds.Count;
            }

            File.WriteAllText(OutputPath, newContent, new UTF8Encoding(false));
            AssetDatabase.ImportAsset(OutputPath);
            return dialogueIds.Count + itemBaseIds.Count;
        }

        // T-01 → T_01,  diary → Diary,  key.stairs_4f → Key_Stairs_4F
        private static string MakeConstName(string id)
        {
            var sb = new StringBuilder(id.Length);
            bool capNext = true;
            foreach (var c in id)
            {
                if (c == '-' || c == '.' || c == ' ')
                {
                    sb.Append('_');
                    capNext = true;
                }
                else if (char.IsLetterOrDigit(c) || c == '_')
                {
                    sb.Append(capNext ? char.ToUpperInvariant(c) : c);
                    capNext = false;
                }
                // skip other punctuation entirely
            }
            // C# const can't start with a digit
            if (sb.Length > 0 && char.IsDigit(sb[0])) sb.Insert(0, '_');
            return sb.ToString();
        }
    }
}
