// AUTO-GENERATED by Editor/FlagKeysGenerator. DO NOT EDIT BY HAND.
// Hand-written entries live in FlagKeysBuiltin.cs.
// Re-run via: Tools > Prism Zone > Import Text Table

namespace PrismZone.Core
{
    public static partial class FlagKeys
    {
        public static class Dialogue
        {
            public const string T_01 = "dialogue.T-01.triggered";
            public const string T_02 = "dialogue.T-02.triggered";
            public const string T_03 = "dialogue.T-03.triggered";
            public const string T_04 = "dialogue.T-04.triggered";
            public const string T_05 = "dialogue.T-05.triggered";
            public const string T_06 = "dialogue.T-06.triggered";
            public const string T_07 = "dialogue.T-07.triggered";
            public const string T_08 = "dialogue.T-08.triggered";
            public const string T_09 = "dialogue.T-09.triggered";
            public const string T_10 = "dialogue.T-10.triggered";
            public const string T_11 = "dialogue.T-11.triggered";
            public const string T_12 = "dialogue.T-12.triggered";
            public const string T_13 = "dialogue.T-13.triggered";
            public const string T_14 = "dialogue.T-14.triggered";
            public const string T_15 = "dialogue.T-15.triggered";
            public const string T_17 = "dialogue.T-17.triggered";
            public const string T_18 = "dialogue.T-18.triggered";
            public const string T_19 = "dialogue.T-19.triggered";
            public const string T_20 = "dialogue.T-20.triggered";
            public const string T_21 = "dialogue.T-21.triggered";
        }

        public static class Inventory
        {
            public const string Has_Diary = "inventory.has.diary";
            public const string Has_Diary_Page_1 = "inventory.has.diary.page.1";
            public const string Has_Diary_Page_2 = "inventory.has.diary.page.2";
            public const string Has_Diary_Page_3 = "inventory.has.diary.page.3";
            public const string Has_Diary_Page_4 = "inventory.has.diary.page.4";
            public const string Has_Glasses = "inventory.has.glasses";
            public const string Has_Glasses_Page_1 = "inventory.has.glasses.page.1";
            public const string Has_Key_Stairs_4f = "inventory.has.key.stairs_4f";
            public const string Has_Key_Stairs_4f_Page_1 = "inventory.has.key.stairs_4f.page.1";
            public const string Has_Key_Storage = "inventory.has.key.storage";
            public const string Has_Key_Storage_Page_1 = "inventory.has.key.storage.page.1";
            public const string Has_Love_letter = "inventory.has.love_letter";
            public const string Has_Love_letter_Page_1 = "inventory.has.love_letter.page.1";
            public const string Has_Mock_note_01 = "inventory.has.mock_note_01";
            public const string Has_Mock_note_01_Page_1 = "inventory.has.mock_note_01.page.1";
            public const string Has_Mock_note_02 = "inventory.has.mock_note_02";
            public const string Has_Mock_note_02_Page_1 = "inventory.has.mock_note_02.page.1";
            public const string Has_Mock_note_03 = "inventory.has.mock_note_03";
            public const string Has_Mock_note_03_Page_1 = "inventory.has.mock_note_03.page.1";
            public const string Has_Old_note = "inventory.has.old_note";
            public const string Has_Old_note_Page_1 = "inventory.has.old_note.page.1";
            public const string Has_Recorder = "inventory.has.recorder";
            public const string Has_Recorder_Page_1 = "inventory.has.recorder.page.1";
        }
    }
}
